theme: jekyll-theme-minimal
title: saintjohncathedral's homepage
description:  Saint John Catholic Cathedral is located in Bauchi, Nigeria. A place of worship, community, and heritage, serving the faithful with love and tradition.
